### ISSUE TITLE
1.15.12 部署失败

### ISSUE THREAD

**Issue by zcola** [kuberenetes-learning-group/fuse-device-plugin#2]
I0729 22:14:49.908801   26292 controller_utils.go:202] Controller kube-system/fuse-device-plugin-daemonset either never recorded expectations, or the ttl expired.
I0729 22:14:49.908956   26292 controller_utils.go:219] Setting expectations &controller.ControlleeExpectations{add:1, del:0, key:"kube-system/fuse-device-plugin-daemonset", timestamp:time.Time{wall:0xc038cbd6762d78b0, ext:301205201534662, loc:(*time.Location)(0x7340ba0)}}
I0729 22:14:49.909001   26292 daemon_controller.go:1015] Nodes needing daemon pods for daemon set fuse-device-plugin-daemonset: [tmax-k8stestnode01-syztest.i.nease.net], creating 1
I0729 22:14:49.962785   26292 controller_utils.go:589] Controller fuse-device-plugin-daemonset created pod fuse-device-plugin-daemonset-2mdlg
I0729 22:14:49.962833   26292 daemon_controller.go:1081] Pods to delete for daemon set fuse-device-plugin-daemonset: [], deleting 0
I0729 22:14:49.962859   26292 controller_utils.go:191] Controller still waiting on expectations &controller.ControlleeExpectations{add:1, del:0, key:"kube-system/fuse-device-plugin-daemonset", timestamp:time.Time{wall:0xc038cbd6762d78b0, ext:301205201534662, loc:(*time.Location)(0x7340ba0)}}
I0729 22:14:49.962874   26292 event.go:258] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"fuse-device-plugin-daemonset", UID:"dae8d5d8-74db-4558-9de9-7cab62b2603c", APIVersion:"apps/v1", ResourceVersion:"2291645", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: fuse-device-plugin-daemonset-2mdlg
I0729 22:14:49.962912   26292 daemon_controller.go:506] Pod fuse-device-plugin-daemonset-2mdlg added.
I0729 22:14:49.962937   26292 disruption.go:382] addPod called on pod "fuse-device-plugin-daemonset-2mdlg"
I0729 22:14:49.962965   26292 daemon_controller.go:1148] Updating daemon set status
I0729 22:14:49.962935   26292 controller_utils.go:236] Lowered expectations &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/fuse-device-plugin-daemonset", timestamp:time.Time{wall:0xc038cbd6762d78b0, ext:301205201534662, loc:(*time.Location)(0x7340ba0)}}
I0729 22:14:49.962967   26292 taint_manager.go:394] Noticed pod update: types.NamespacedName{Namespace:"kube-system", Name:"fuse-device-plugin-daemonset-2mdlg"}
I0729 22:14:49.962986   26292 disruption.go:457] No PodDisruptionBudgets found for pod fuse-device-plugin-daemonset-2mdlg, PodDisruptionBudget controller will avoid syncing.
I0729 22:14:49.963003   26292 disruption.go:385] No matching pdb for pod "fuse-device-plugin-daemonset-2mdlg"
I0729 22:14:49.962989   26292 pvc_protection_controller.go:280] Got event on pod kube-system/fuse-device-plugin-daemonset-2mdlg
I0729 22:14:50.004259   26292 daemon_controller.go:1210] Finished syncing daemon set "kube-system/fuse-device-plugin-daemonset" (116.519859ms)
I0729 22:14:50.004285   26292 daemon_controller.go:183] Updating daemon set fuse-device-plugin-daemonset
I0729 22:14:50.004492   26292 controller_utils.go:185] Controller expectations fulfilled &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/fuse-device-plugin-daemonset", timestamp:time.Time{wall:0xc038cbd6762d78b0, ext:301205201534662, loc:(*time.Location)(0x7340ba0)}}
I0729 22:14:50.004555   26292 controller_utils.go:219] Setting expectations &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/fuse-device-plugin-daemonset", timestamp:time.Time{wall:0xc038cbd6804574ad, ext:301205297136785, loc:(*time.Location)(0x7340ba0)}}
I0729 22:14:50.004566   26292 daemon_controller.go:1015] Nodes needing daemon pods for daemon set fuse-device-plugin-daemonset: [], creating 0
I0729 22:14:50.004583   26292 daemon_controller.go:1081] Pods to delete for daemon set fuse-device-plugin-daemonset: [], deleting 0
I0729 22:14:50.004588   26292 controller_utils.go:185] Controller expectations fulfilled &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/fuse-device-plugin-daemonset", timestamp:time.Time{wall:0xc038cbd6804574ad, ext:301205297136785, loc:(*time.Location)(0x7340ba0)}}
I0729 22:14:50.004607   26292 daemon_controller.go:1148] Updating daemon set status
I0729 22:14:50.004646   26292 daemon_controller.go:1210] Finished syncing daemon set "kube-system/fuse-device-plugin-daemonset" (351.053µs)
I0729 22:14:50.004800   26292 controller_utils.go:185] Controller expectations fulfilled &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/fuse-device-plugin-daemonset", timestamp:time.Time{wall:0xc038cbd6804574ad, ext:301205297136785, loc:(*time.Location)(0x7340ba0)}}

**Comment by soolaugust** [comment]
从日志看应该是创建成功了，还有其他的日志么？

```log
I0729 22:14:49.962874 26292 event.go:258] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"fuse-device-plugin-daemonset", UID:"dae8d5d8-74db-4558-9de9-7cab62b2603c", APIVersion:"apps/v1", ResourceVersion:"2291645", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: fuse-device-plugin-daemonset-2mdlg
I0729 22:14:49.962912 26292 daemon_controller.go:506] Pod fuse-device-plugin-daemonset-2mdlg added.
I0729 22:14:49.962937 26292 disruption.go:382] addPod called on pod "fuse-device-plugin-daemonset-2mdlg"
I0729 22:14:49.962965 26292 daemon_controller.go:1148] Updating daemon set status
I0729 22:14:49.962935 26292 controller_utils.go:236] Lowered expectations &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/fuse-device-plugin-daemonset", timestamp:time.Time{wall:0xc038cbd6762d78b0, ext:301205201534662, loc:(*time.Location)(0x7340ba0)}}
I0729 22:14:49.962967 26292 taint_manager.go:394] Noticed pod update: types.NamespacedName{Namespace:"kube-system", Name:"fuse-device-plugin-daemonset-2mdlg"}
```

**Comment by zcola** [comment]
后面还是再宿主上挂了fuse ，谢谢啊
